-- Skema database Undangan Pernikahan Dendi & Amora
-- MySQL 5.7+/MariaDB 10.3+ (utf8mb4)

SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS admins (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(60) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  last_login_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS wedding_settings (
  id TINYINT UNSIGNED PRIMARY KEY,
  groom_name VARCHAR(80) NOT NULL,
  groom_full_name VARCHAR(160) NOT NULL DEFAULT '',
  groom_family VARCHAR(200) NOT NULL DEFAULT '',
  bride_name VARCHAR(80) NOT NULL,
  bride_full_name VARCHAR(160) NOT NULL DEFAULT '',
  bride_family VARCHAR(200) NOT NULL DEFAULT '',
  bride_family_confirmed TINYINT(1) NOT NULL DEFAULT 0,
  opening_text TEXT NULL,
  closing_text TEXT NULL,
  theme_settings JSON NULL,
  content JSON NULL,
  published TINYINT(1) NOT NULL DEFAULT 0,
  published_snapshot JSON NULL,
  published_at DATETIME NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS events (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  event_type VARCHAR(80) NOT NULL,
  event_date DATE NULL,
  start_time TIME NULL,
  end_time TIME NULL,
  end_label VARCHAR(40) NOT NULL DEFAULT '',
  timezone VARCHAR(40) NOT NULL DEFAULT 'Asia/Jakarta',
  venue_name VARCHAR(160) NOT NULL DEFAULT '',
  address TEXT NULL,
  maps_url VARCHAR(500) NOT NULL DEFAULT '',
  sort_order INT NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS gallery (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  file_path VARCHAR(255) NOT NULL,
  thumb_path VARCHAR(255) NOT NULL,
  width INT UNSIGNED NOT NULL,
  height INT UNSIGNED NOT NULL,
  caption VARCHAR(160) NOT NULL DEFAULT '',
  sort_order INT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS guests (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  guest_name VARCHAR(160) NOT NULL,
  name_key VARCHAR(160) NOT NULL,
  category VARCHAR(80) NOT NULL DEFAULT '',
  phone VARCHAR(30) NOT NULL DEFAULT '',
  invitation_code VARCHAR(16) NOT NULL UNIQUE,
  max_companions TINYINT UNSIGNED NULL,
  notes VARCHAR(500) NOT NULL DEFAULT '',
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  opened_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_name_key (name_key),
  INDEX idx_category (category)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rsvps (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  guest_id INT UNSIGNED NOT NULL UNIQUE,
  status ENUM('hadir','tidak_hadir','ragu') NOT NULL,
  guest_count TINYINT UNSIGNED NOT NULL DEFAULT 0,
  message VARCHAR(500) NOT NULL DEFAULT '',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_rsvp_guest FOREIGN KEY (guest_id) REFERENCES guests(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS wishes (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  guest_id INT UNSIGNED NULL,
  guest_name VARCHAR(80) NOT NULL,
  message VARCHAR(500) NOT NULL,
  status ENUM('pending','approved','hidden') NOT NULL DEFAULT 'pending',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_status (status),
  CONSTRAINT fk_wish_guest FOREIGN KEY (guest_id) REFERENCES guests(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rate_limits (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  bucket VARCHAR(40) NOT NULL,
  ident CHAR(64) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_bucket (bucket, ident, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
